(include_subdirs unqualified)

(library
 (name yescrypt)
 (public_name ocaml-yescrypt)
 (libraries ctypes ctypes.stubs ctypes-foreign ocaml-yescrypt.bindings)
 (modules
   yescrypt
   yescrypt_internal
   yescrypt_flags
   yescrypt_generated
 )

 (foreign_stubs
  (language c)
  (names
    yescrypt_stubs ; Generated stubs (needed for linking)
    yescrypt-common
    yescrypt-platform
    yescrypt-ref
    sha256
    insecure_memzero
  )
  (flags -I c_lib/)
 )
)

; Rule to generate yescrypt_stubs.c + yescrypt_generated.ml in lib/
(rule
 (targets yescrypt_stubs.c yescrypt_generated.ml)
 (deps ../lib_gen/yescrypt_bindgen.exe)
 (action (run ../lib_gen/yescrypt_bindgen.exe))
)